manipulator:
  kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
  kinematics_solver_timeout: 0.005
  solver_type: Speed   
  #solver type can use : Speed, Distance, Manipulation1, Manipulation2
